# This project uses requirements.txt for dependency management
# pyproject.toml is used only for tool configuration (pytest, ruff, mypy, bandit)

# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--tb=short",
    "--disable-warnings",
    "--color=yes",
    "--cov=app",
    "--cov-report=term-missing"
]
asyncio_mode = "auto"

# ==== Coverage ====
[tool.coverage.run]
source = ["app"]
omit = [
    "*/tests/*",
    "*/venv/*",
    "*/.venv/*",
    "*/__pycache__/*",
    "venv/*",
    ".venv/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise AssertionError",
    "raise NotImplementedError",
]

# ==== mypy ====
[tool.mypy]
python_version = "3.12"
check_untyped_defs = false           # Don't check untyped function definitions
ignore_missing_imports = true
warn_unused_ignores = false          # Don't warn about unused type ignores
warn_redundant_casts = false         # Don't warn about redundant casts
warn_unused_configs = false          # Don't warn about unused configs
warn_return_any = false              # Allow Any returns
warn_unreachable = false             # Don't warn about unreachable code
strict_optional = false              # Allow implicit Optional
disallow_untyped_calls = false
disallow_untyped_defs = false        # Allow functions without return type annotations
disallow_incomplete_defs = false     # Allow functions without parameter type annotations

# Suppress specific error codes
disable_error_code = [
    "call-arg",          # Suppress call argument errors
    "assignment",        # Suppress assignment type errors  
    "attr-defined",      # Suppress attribute defined errors
    "dict-item",         # Suppress dict item type errors
    "arg-type"           # Suppress argument type errors
]

# Exclude problematic files and directories (regex patterns)
exclude = [
    "venv/.*",
    "\\.venv/.*", 
    "conftest\\.py",
    "tests/.*",
    "app/services/.*",       # Services have external dependencies causing type issues
    "app/tools/.*",          # Tools might have complex types
    "app/core/.*",           # Core logic has complex types
    "app/utils/.*",          # Utilities have edge cases
    "app/models/actions\\.py",  # Has specific type issues with field names
    "app/api/routes/chat\\.py"  # Has type issues with response models
]

# ==== ruff ====
[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    "build",
    "dist",
]

[tool.ruff.lint]
select = [
    "F",     # Pyflakes
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "C90",   # mccabe
    "I",     # isort
    "N",     # pep8-naming
    "UP",    # pyupgrade
    "S",     # flake8-bandit
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "PIE",   # flake8-pie
    "PT",    # flake8-pytest-style
    "RET",   # flake8-return
    "SIM",   # flake8-simplify
    "PTH",   # flake8-use-pathlib
    "PL",    # Pylint
    "RUF",   # Ruff-specific rules
]
ignore = [
    "S101",   # Use of assert detected
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
]

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["app"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "PLR0913", "PLR2004", "ARG001"]
"conftest.py" = ["S101"]

# ==== bandit ====
[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv"]
skips = ["B101", "B601"] 