name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-nextjs:
    name: Test and Lint Next.js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.20.0'

      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Copy environment variables
        run: cp .env.example .env

      - name: Start Docker services
        run: docker compose up -d postgres

      - name: Run ESLint
        run: bun run lint

      - name: Run typecheck
        run: bun run typecheck

      - name: Run tests
        run: bun run test

      - name: Build application
        run: bun run build
