name: Release to Production

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: 'mobile-release-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build-mobile-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        working-directory: mobile
        run: npm ci

      - name: Build and publish mobile apps (EAS)
        working-directory: mobile
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          # Build iOS app for TestFlight
          eas build --platform ios --profile production --non-interactive --auto-submit

          # Build Android app for Google Play (if you want to include Android)
          # eas build --platform android --profile production --non-interactive --auto-submit

      - name: Notify Slack - Success
        if: success()
        run: |
          curl -X POST --data '{"text":"📱 Mobile App Release ${{ github.ref_name }} Built and Published Successfully"}' ${{ secrets.SLACK_DEV_CHANNEL_WEBHOOK_URL }}

      - name: Notify Slack - Failure
        if: failure()
        run: |
          curl -X POST --data "{\"text\":\"❌ Mobile App Release ${{ github.ref_name }} Build Failed\nAction: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" ${{ secrets.SLACK_DEV_CHANNEL_WEBHOOK_URL }}
